import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./shared/organisms/Sidebar";
import { SidebarProvider } from "./shared/organisms/SidebarContext";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "./auth/organisms/AuthProvider";
import { DemoBanner } from "@/components/ui/demo-banner";
import TransitionLayout from "./transition-layout";
import { ReplicacheProviders } from "./shared/organisms/ReplicacheProviders";
import { SyncStatus } from "./shared/molecules/SyncStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirmatn.variable} antialiased`}
      >
        <AuthProvider>
          <SidebarProvider>
            <DemoBanner />
            <Sidebar />
            <ReplicacheProviders>
              <TransitionLayout>
                <main className="md:pt-0 md:ml-64 transition-all duration-300">
                  {children}
                </main>
                {/* Global Sync Status - Fixed Position */}
                <div className="fixed top-4 right-4 z-50">
                  <SyncStatus />
                </div>
              </TransitionLayout>
            </ReplicacheProviders>
          </SidebarProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
