import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./shared/organisms/Sidebar";
import { SidebarProvider } from "./shared/organisms/SidebarContext";
import { ChangelogProvider } from "@/app/shared/organisms/ChangelogProvider";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "./auth/organisms/AuthProvider";
import { DemoBanner } from "@/components/ui/demo-banner";
import { ReplicacheTodoProvider } from "./todo/atoms/ReplicacheTodoContext";
import TransitionLayout from "./transition-layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vazirmatn = Vazirmatn({
  variable: "--font-vazirmatn",
  subsets: ["arabic", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazirmatn.variable} antialiased`}
      >
        <AuthProvider>
          <ChangelogProvider>
            <SidebarProvider>
              <DemoBanner />
              <Sidebar />
              <ReplicacheTodoProvider>
                <TransitionLayout>
                  <main className="md:pt-0 md:ml-64 transition-all duration-300">
                    {children}
                  </main>
                </TransitionLayout>
              </ReplicacheTodoProvider>
            </SidebarProvider>
          </ChangelogProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
