import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "./shared/organisms/Sidebar";
import { SidebarProvider } from "./shared/organisms/SidebarContext";
import { ChangelogProvider } from "@/app/shared/organisms/ChangelogProvider";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "./auth/organisms/AuthProvider";
import { DemoBanner } from "@/components/ui/demo-banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ChangelogProvider>
            <SidebarProvider>
              <DemoBanner />
              <Sidebar />
              <main className="md:pt-0 md:ml-64 transition-all duration-300">
                {children}
              </main>
            </SidebarProvider>
          </ChangelogProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
